### ISSUE TITLE
【紧急/无法打开】一个老问题

### ISSUE THREAD

**Issue by xiaohuangbo** [FurryR/guestbook#1]
之前该博客使用EAGE浏览器都可以打开，但重构代码之后就是一片黑，不能输入任何字符也没有任何输出，已启用COOKIES和JAVASCRIPT，在safari浏览器下都正常，且可以正常输入和输出，但在eage浏览器下就不能正常打开，截图如下：
![image](https://user-images.githubusercontent.com/69374707/198638848-daf220c3-98d0-4693-8dd3-1aeba0f48001.png)
![image](https://user-images.githubusercontent.com/69374707/198640917-c932a621-4d38-4296-82c5-e84a5ac90ccc.png)
![image](https://user-images.githubusercontent.com/69374707/198643196-d66d1729-8498-47bb-a433-19f630655c2e.png)

（备注：浏览器插件都是禁用了的，有些也没发挥作用，eage浏览器版本是108.0.1438.1 (正式版本) dev (64 位)
）

**Comment by FurryR** [comment]
我无法复现此问题。
我发现你的页面内容好像被插件更改了，是否需要禁用所有插件？

**Comment by FurryR** [comment]
如果禁用插件后问题仍然出现，请转到Console并复制信息。

**Comment by xiaohuangbo** [comment]
这次我禁用了全部插件，问题仍然存在
![image](https://user-images.githubusercontent.com/69374707/198824690-061d1a5a-41ca-4233-b169-cece85f7c100.png)
![image](https://user-images.githubusercontent.com/69374707/198824726-608ea817-919b-4b73-be55-6af316ef9d7d.png)
![image](https://user-images.githubusercontent.com/69374707/198825442-e53706e3-4cb8-4de7-9cff-e71fc7fbd58b.png)
我应该复制哪些信息？

**Comment by FurryR** [comment]
Console的，谢谢。

**Comment by xiaohuangbo** [comment]
问题已解决，是我浏览器的问题XD
![Screenshot_20221223_222526](https://user-images.githubusercontent.com/69374707/209351452-49585fb5-1c53-4f47-9d54-4e4ba5e0cb19.jpg)
